vaadin.launch-browser=true
spring.application.name=OLMP

spring.datasource.url=jdbc:postgresql://localhost:5432/olmp_db
spring.datasource.username=olmp_user
spring.datasource.password=olmp_password

spring.jpa.hibernate.ddl-auto=none