spring.application.name=OLMP

spring.datasource.url=jdbc:postgresql://localhost:5432/olmp_db
spring.datasource.username=olmp_user
spring.datasource.password=olmp_password

spring.jpa.hibernate.ddl-auto=none

olmp.security.jwt.issuer=olmp
olmp.security.jwt.secret=${OLMP_JWT_SECRET:change-me-in-prod-change-me-in-prod-change-me-in-prod-change-me-in-prod}
olmp.security.jwt.access-token-ttl=PT30M